# Generated by Django 4.2.6 on 2024-07-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_music_database_music_criteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='music_database',
            name='Music_Banner',
            field=models.ImageField(upload_to='Banner'),
        ),
        migrations.AlterField(
            model_name='music_database',
            name='Music_File',
            field=models.FileField(upload_to='Music'),
        ),
    ]
