# Generated by Django 4.2.6 on 2024-07-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_artist_alter_music_database_music_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='Image',
            field=models.ImageField(default=1, upload_to='Artist'),
        ),
    ]
