# Generated by Django 4.2.6 on 2024-07-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_artist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='Artist'),
        ),
    ]
